# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [148]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [150]:
chipo.item_price = chipo.item_price.str.replace('$', '')
chipo
print(chipo.item_price.dtype)
chipo.item_price = chipo.item_price.astype(float)
print(chipo.item_price.dtype)

object
float64

In [152]:
chipo["precio_unidad"] = chipo.item_price / chipo.quantity
precios_min = chipo.groupby("item_name")["precio_unidad"].min().idxmax()

In [153]:
chipo.groupby("item_name")["precio_unidad"].min().idxmax()

'Barbacoa Salad Bowl'

In [154]:
precios_min = chipo.groupby("item_name")["precio_unidad"].min()
precio_max = precios_min.max()
productos_max = precios_min[precios_min == precio_max]
productos_max

item_name
Barbacoa Salad Bowl    9.39
Carnitas Salad Bowl    9.39
Steak Salad Bowl       9.39
Name: precio_unidad, dtype: float64

In [ ]:
""" indice = chipo.precio_unidad.idxmax()
print(chipo.iloc[indice].item_name, end=" ")
print(chipo.iloc[indice].choice_description) """

Steak Salad Bowl [Tomatillo Red Chili Salsa, [Black Beans, Cheese, Guacamole]]

### Step 4. How many products cost more than $10.00?

In [156]:
print(len(precios_min[precios_min > 10]))

0

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [133]:
suma_pedidos = chipo.groupby("order_id")["item_price"].sum()
print(len(suma_pedidos[suma_pedidos > 10]))

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [138]:
print(len(chipo[chipo["quantity"] > 1][chipo["item_price"] > 10]))

133

C:\Users\Asier\AppData\Local\Temp\ipykernel_2672\1091301748.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(chipo[chipo["quantity"] > 1][chipo["item_price"] > 10]))

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [140]:
chipo[["item_name", "precio_unidad"]]

                                  item_name  precio_unidad
0              Chips and Fresh Tomato Salsa           2.39
1                                      Izze           3.39
2                          Nantucket Nectar           3.39
3     Chips and Tomatillo-Green Chili Salsa           2.39
4                              Chicken Bowl           8.49
...                                     ...            ...
4617                          Steak Burrito          11.75
4618                          Steak Burrito          11.75
4619                     Chicken Salad Bowl          11.25
4620                     Chicken Salad Bowl           8.75
4621                     Chicken Salad Bowl           8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [141]:
chipo[["item_name", "precio_unidad"]].sort_values("item_name")

              item_name  precio_unidad
3389  6 Pack Soft Drink           6.49
341   6 Pack Soft Drink           6.49
1849  6 Pack Soft Drink           6.49
1860  6 Pack Soft Drink           6.49
2713  6 Pack Soft Drink           6.49
...                 ...            ...
2384  Veggie Soft Tacos           8.75
781   Veggie Soft Tacos           8.75
2851  Veggie Soft Tacos           8.49
1699  Veggie Soft Tacos          11.25
1395  Veggie Soft Tacos           8.49

[4622 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [162]:
indice = chipo.item_price.idxmax()
print(chipo.quantity.iloc[indice])

15

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [166]:
print(len(chipo[chipo.item_name == "Veggie Salad Bowl"]))

18

### Step 9. How many times did someone order more than one Canned Soda?

In [168]:
print(len(chipo[chipo.item_name == "Canned Soda"][chipo.quantity > 1]))

20

C:\Users\Asier\AppData\Local\Temp\ipykernel_2672\1100903731.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(len(chipo[chipo.item_name == "Canned Soda"][chipo.quantity > 1]))